export const blocks = [
	{
		name:"sudo",
		color:"rgb(0,255,0)",
		fontWeight:"bolder",
		border:"none",
		textColor:"black",
	},
	{
		name:"apt",
		color:"white",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"install",
		color:"rgb(100, 150, 255)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"cd",
		color:"rgb(145, 145, 145)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"ipconfig",
		color:"rgb(227, 100, 255)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"ping",
		color:"rgb(227, 100, 255)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"text",
		color:"white",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"exit",
		color:"rgb(100, 150, 255)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"touch",
		color:"white",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"open",
		color:"rgb(0,255,0)",
		fontWeight:"bolder",
		border:"none",
		textColor:"black",
	},
	{
		name:"help",
		color:"white",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"del",
		color:"rgb(100, 150, 255)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"mkdir",
		color:"rgb(145, 145, 145)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"rmdir",
		color:"rgb(145, 145, 145)",
		fontWeight:"normal",
		border:"none",
		textColor:"black",
	},
	{
		name:"restart",
		color:"rgb(223, 86, 86)",
		fontWeight:"bolder",
		border:"none",
		textColor:"black",
	},
]